name: Main build & deploy
on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: false
  NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 0
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout [Pull Request]
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: actions/checkout@v4
        name: Checkout [Default Branch]
        if: ${{ github.event_name != 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run build task
        run: pnpm nx affected -t build

      - name: Run deploy task
        run: |
          pnpm nx affected -t deploy > deployment.log

      - name: Get deployment link
        id: dep_link
        run: echo "link=$(cat /.github/deployment_link.txt)" > $GITHUB_OUTPUT

      - name: Publish deployment link
        uses: actions/github-script@v4
        with:
          script: |
            const { GitHub } = require('@actions/github');
            const github = new GitHub(${{ secrets.GITHUB_TOKEN }});
            const issueNumber = '${{ github.event.number }}'
            const link = '${{ steps.dep_link.outputs.link }}';
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `### QA Deployment
              result: ${link}`
            });
